---
abstract: 'Install modules I like'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-hanekomu
provides:
  Task::BeLike::hanekomu:
    file: lib/Task/BeLike/hanekomu.pm
    version: 1.100810
requires:
  AnyEvent: 0
  App::Ack: 0
  App::Rgit: 0
  App::cpanminus: 0
  App::cpanoutdated: 0
  Carp: 0
  Coro: 0
  DBD::SQLite: 0
  DBI: 0
  Devel::Loaded: 0
  Devel::NYTProf: 0
  Devel::SearchINC: 0
  Dist::Zilla::PluginBundle::MARCEL: 0
  English: 0
  File::Find: 0
  File::Slurp: 0
  File::Temp: 0
  File::Which: 0
  LWP: 0
  Perl::Tidy: 0
  Plack: 0
  Pod::Weaver::PluginBundle::MARCEL: 0
  Pod::Wordlist::hanekomu: 0
  Scalar::Util: 0
  Task::Dist::Zilla: 0
  Test::Differences: 0
  Test::More: 0.88
  Web::Scraper: 0
  YAML: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-hanekomu
  homepage: http://search.cpan.org/dist/Task-BeLike-hanekomu/
  repository: http://github.com/hanekomu/Task-BeLike-hanekomu
version: 1.100810
